name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kilikia
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kilikia/aca_test:latest
      - run:  |
          mkdir -p ~/.ssh
          touch ~/key
          echo $SSH_PRIVATE_KEY > ~/key
          sudo chmod 600 ~/key
          cp ~/key ~/.ssh/id_rsa

        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh -o "StrictHostKeyChecking no" grigor@109.68.120.122 'docker rm -fv nginx && docker run --name nginx -d -p 80:80 kilikia/aca_test'
