name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run:  |
	  export AWS_ACCESS_KEY_ID:"${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY:"${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_REGION="us-east-1"
          mkdir -p ~/.ssh
          touch ~/key
          echo $SSH_PRIVATE_KEY_AWS > ~/key
          sudo chmod 600 ~/key
          cp ~/key ~/.ssh/id_rsa
	  terraform apply | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" >> inventory-ansible 
	  truncate -s-1 inventory-ansible
	  echo -n " ansible_user=ubuntu ansible_ssh_private_key_file=~/key" >> inventory-ansible
          ansible-playbook docker-ansible.yaml --ssh-common-args='-o StrictHostKeyChecking=no' -i inventory-ansible
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_AWS}}
