name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
        - run:  export AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          shell: bash
        - run:  export AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        - run:  export AWS_REGION= "us-east-1"
        - run:  mkdir -p ~/.ssh
        - run:  touch ~/key
        - run:  echo $SSH_PRIVATE_KEY_AWS > ~/key
        - run:  sudo chmod 600 ~/key
        - run:  cp ~/key ~/.ssh/id_rsa
        - run:  terraform apply | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" >> inventory-ansible 
        - run:  truncate -s-1 inventory-ansible
        - run:  echo -n " ansible_user=ubuntu ansible_ssh_private_key_file=~/key" >> inventory-ansible
        - run:  ansible-playbook docker-ansible.yaml --ssh-common-args='-o StrictHostKeyChecking=no' -i inventory-ansible
          shell: bash
          env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_AWS}}
